### ISSUE TITLE
Question of UT-HAR data

### ISSUE THREAD

**Issue by NJUPT-Sivan** [CHENXINYAN-sg/WiFi-CSI-Sensing-Benchmark#1]
After reading your paper 《Deep Learning and Its Applications to WiFi Human Sensing: A Benchmark and A Tutorial 》, I think it is great. However, I ran into some problems when I reproduced with code and dataset. I've done some work on human activity recognition using yousefi's dataset before. Currently I have several questions:
- I downloaded the UT-HAR dataset from your Google Drive link, but when I try to open these CSV files it shows a bunch of garbled characters, after changing the encoding I still can't solve this problem. As this picture shows that:![](https://raw.githubusercontent.com/NJUPT-Sivan/PicGo1/main/img/202208291816909.png)
- I have read yousefi's paper 《A survey on behavior recognition using WiFi channel state information》，this paper offers a dataset which has many CSV files, I would like to know what did you do with this dataset to make it into the three CSV files of train-valid-test.
- It is normal for me to run other datasets with your code, but an error occurs when running this UT_HAR_data dataset, as shown in the following figure![](https://raw.githubusercontent.com/NJUPT-Sivan/PicGo1/main/img/202208291825128.png)
Thanks a lot for your paper which makes me achieved a lot, and I look forward to getting your answers and help.

**Comment by CHENXINYAN-sg** [comment]
1. This dues to the encoding problem. You can load the UT_HAR dataset first (indicated as the function 'UT_HAR_dataset' in dataset.py) and then read the data.

2. After getting raw data from yousefi's paper, you may follow the instructions in their github (link is given). They use sliding window method to generate data and seprate into 7 files according to the corresponding labels. We then use a train-val-test ratio of 8:1:1 to split each file and finally merge the data for all labels together to get three CSV files.

3. The cause of this problem is that our code is based on Linux system. If you want to use Windows system to run the code, you may change the "/" in dataset.py line 13 and line 20 into "\\".
